### PR TITLE
Properly support 3.5

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by ogrisel** [comment]
Does it work? As far as I can see this is not tested.

**Comment by nedbat** [comment]
I'm not sure what kind of tests you are looking for.  This works much better than without this change: https://ci.appveyor.com/project/nedbat/coveragepy though there still seem to be problems with the 64-bit builds.

**Comment by ogrisel** [comment]
A new entry in the `appveyor.yml` file of this repo. But as I said earlier we also need to add a bypass in the `.cmd` script to avoid trying to setup the old SDK environment when building with Python 3.5 and later.

**Comment by nedbat** [comment]
There was already a 3.5.0rc2 clause in appveyor.yml, but I went ahead and added the 64-bit as well, and also for 2.6.
I'll try my hand at the .cmd bypass...

**Comment by nedbat** [comment]
The .cmd file will do the right thing if I can get the minor version comparison against 4 working properly. :(

**Comment by ogrisel** [comment]
> The .cmd file will do the right thing if I can get the minor version comparison against 4 working properly. :(

Welcome to the club. I still do not understand how string operations work in `.cmd` files even though I am the author of that file...

**Comment by nedbat** [comment]
@ogrisel This now works on all of the jobs.
I learned something about string operations, and put a comment at the top with what I learned.
I also learned that there are still mysteries of batch files that I don't understand.
But it works. :)

**Comment by ogrisel** [comment]
Thanks si much! Merging.

**Pull request merged**
